---
- name: abrir puertos
  ansible.posix.firewalld:
    zone: public
    port: 80/tcp
    permanent: yes
    immediate: true
    state: enabled
- name: sabrir puertos
  ansible.posix.firewalld:
    zone: public
    port: 80/tcp
    permanent: yes
    immediate: true
    state: enabled





- name: Update
  dnf:
    name: "*"
    state: latest

- name: Install nginx
  dnf:
    name: "nginx"
    state: present
  become: yes

- name: Start and enable service nginx
  service:
    name: "nginx" 
    state: started
  become: yes  

